Update runtime
flathub/com.plexamp.Plexamp pull request #100
Opened 2023-12-14 01:55 UTC by hdonnay

As noted in #87, I figured out a way around a crash on newer runtimes.
These changes fix that and update the runtime.

It'd be much nicer if the Plexamp application were just built as a flatpak natively, but that would probably mean building it on Plex, Inc. infrastructure and then uploading to flathub. The only flatpak I know of that's done that way is Firefox. It may be something for the Plex "linux guy" to look into if there's ever spare time.

2023-12-14 22:51 UTC, simonxciv requested changes
Thanks so much for the PR! The underlying issue is actually in our native networking stack, but requires some considerable work before it's ready to resolve this issue. In the meantime, this workaround looks good to me. A couple of (hopefully) quick notes, and I'll be happy to merge and push out a new release with these changes.

2023-12-14 22:51 UTC, simonxciv commented on com.plexamp.Plexamp.yaml
> +      - cacert.pem
We can't remove this cert. AFAIK it's used for more than just the updater. Off the top of my head, I believe it's required for relayed server connections.

2023-12-14 22:51 UTC, simonxciv commented on com.plexamp.Plexamp.yaml
> +    cleanup:
I just pushed an updated build process that drops the requirement for unappimage completely. Could you please rebase and drop this cleanup step?

2023-12-15 00:19 UTC, hdonnay commented
So, not deleting the certificate causes the crash. I'll explore a few ideas I have for making this work

2023-12-15 02:10 UTC, hdonnay commented
There (perhaps understandably) doesn't seem to be a way to get an additional cert into the sandbox's trust root.

I think any solution here that isn't just nuking this CA bundle is going to require code changes.

2023-12-31 06:17 UTC, simonxciv commented
I've just tested these changes in beta and can confirm that it causes our networking stack to break. Anything that requires SSL will fail.

Plex servers can fallback to non-SSL if configured to do so, so it's not immediately obvious that this was broken.

2024-01-02 18:45 UTC, hdonnay commented
Ah, fair enough -- toggling my PMS to "Required" secure connections does indeed break playback.

I've tried a variant of this that swaps the `cacert.pem` with a link to the runtime cert bundles (both the "short" and "extended" versions), but this also still crashes.

2024-01-02 22:56 UTC, simonxciv commented
I think I've found the source of the problem. We ship a forked and pre-built curl binary. I've not dug into why just yet, but from Plexamp logs, it looks like we're not using that curl build in the flatpak. This is likely causing other subtle bugs on Linux, too.

2024-01-27 17:40 UTC, hdonnay commented
I've tried also building a version with a copy of `openssl-1.1.1w` in the `/app` hierarchy, and still no joy. It seems that `plexamp` binary is linked against `libssl.so.3`, and I can't find another binary in the AppImage files that wants to link against `libssl.so.1`.
<details>
```
% find /app/bin -executable -type f -exec ldd '{}' + | grep '^/app\|ssl'
/app/bin/gvfs-trash:
	not a dynamic executable
/app/bin/notify-send:
/app/bin/zypak-helper:
/app/bin/zypak-sandbox:
/app/bin/zypak-wrapper.sh:
	not a dynamic executable
/app/bin/startplexamp:
	not a dynamic executable
/app/bin/plexamp/AppRun:
	not a dynamic executable
/app/bin/plexamp/chrome_crashpad_handler:
/app/bin/plexamp/libEGL.so:
/app/bin/plexamp/libGLESv2.so:
/app/bin/plexamp/libffmpeg.so:
/app/bin/plexamp/libvk_swiftshader.so:
/app/bin/plexamp/plexamp:
	libssl.so.3 => /usr/lib/x86_64-linux-gnu/libssl.so.3 (0x00007f088cefd000)
/app/bin/plexamp/resources/app.asar.unpacked/node_modules/electron-media-service/build/Release/electron_media_service.node:
/app/bin/plexamp/resources/treble/treble.node:
/app/bin/plexamp/chrome-sandbox:
/app/bin/plexamp/libvulkan.so.1:
```
</details>

So, I'll set this aside and wait for someone with source access to fix it.

2024-03-15 23:39 UTC, closed without merging